server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
